### ISSUE TITLE
migrate to null safety for flutter 2.0

### ISSUE THREAD

**Issue by NeelNakrani** [joostlek/GradientAppBar#23]

**Comment by BringTheChill** [comment]
Yes please @joostlek @iMaz1n

**Comment by X-Wei** [comment]
+1 
pls update the package.

For now I'm using the fork by @TinyProgrammers

```yml
  gradient_app_bar:
    git:
      url: https://github.com/TinyProgrammers/GradientAppBar.git
```
